"""Compare early historical-output omission with budget-triggered omission."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import UTC, datetime
from pathlib import Path

from cobalt.context import prepare_context
from cobalt.domain import ModelTurn, ToolCall
from cobalt.engine import Agent
from cobalt.model import from_config
from cobalt.model_config import resolve_config
from cobalt.tools import ToolGate
from cobalt.workspace import Workspace
from scripts.evaluate_multiturn import run_attempt


class HistoricalAgent(Agent):
    def _model_context(self, retry_hint=""):
        dynamic, _, _, _ = super()._model_context(retry_hint)
        original = list(self.messages)
        original[0] = dynamic[0]
        return prepare_context(original, compact_history=True)


def grade_recall(answer, token, exit_code, executions, actions, evidence_available):
    tokens = re.findall(r"\bRESULT=([A-Za-z0-9_-]+)", answer)
    exits = re.findall(r"\bEXIT=(-?\d+)\b", answer)
    return (bool(tokens) and all(value == token for value in tokens)
            and bool(exits) and all(int(value) == exit_code for value in exits)
            and executions == 1 and evidence_available
            and not any(a["name"] in {"run_command", "create_file", "replace_text"} for a in actions))


def recall_attempt(config, case, policy, attempt, cls):
    with tempfile.TemporaryDirectory(prefix="cobalt-history-") as directory:
        root = Path(directory)
        workspace = Workspace(root)
        exit_code = 7 if case == "recall_failed_log" else 0
        # The secret is generated by the executed program, not present in its source.
        # Its location is visible in a full preview but absent from the compact marker.
        emitter = (
            "import json,secrets,sys; from pathlib import Path; "
            "p=Path('.cobalt/receipt.json'); "
            "n=json.loads(p.read_text())['executions']+1 if p.exists() else 1; "
            "token=secrets.token_hex(24); "
            "p.write_text(json.dumps({'token':token,'executions':n})); "
            + ("out=sys.stderr; " if exit_code else "out=sys.stdout; ")
            + "print('prefix '*400,file=out); print('RESULT='+token,file=out); "
            "print('suffix '*700,file=out); " + f"sys.exit({exit_code})"
        )

        class SetupModel:
            def __init__(self):
                self.turns = iter([
                    ModelTurn("", (ToolCall("emit", "run_command", {"argv": [sys.executable, "-c", emitter]}),)),
                    ModelTurn("Output recorded."),
                ])

            def complete(self, messages, tools):
                return next(self.turns)

        agent = cls(workspace, SetupModel(), ToolGate(workspace, lambda _n, _a: True), max_tool_calls=12)
        agent.ask("Run the diagnostic once. Record the output; I will ask about it later.")
        receipt = json.loads((root / ".cobalt" / "receipt.json").read_text(encoding="utf-8"))
        before = json.loads(json.dumps(agent.messages))
        delegate = from_config(config)

        class ObservedModel:
            saw_token = False

            def complete(self, messages, tools):
                self.saw_token |= any("RESULT=" + receipt["token"] in str(m.get("content", "")) for m in messages)
                return delegate.complete(messages, tools)

        agent.model = ObservedModel()
        agent.tools = ToolGate(workspace, lambda _n, _a: False, read_only=True)
        start = time.monotonic()
        result = agent.ask(
            "Report the exact RESULT token and exit code from the previous diagnostic as RESULT=<token> EXIT=<code>. "
            "Use the recorded output, reading its archive if necessary. Do not run any commands or modify files."
        )
        elapsed = round(time.monotonic() - start, 3)
        after = json.loads((root / ".cobalt" / "receipt.json").read_text(encoding="utf-8"))
        events = [json.loads(line) for line in
                  (root / ".cobalt" / "runs" / result.run_id / "events.jsonl").read_text(encoding="utf-8").splitlines()]
        actions = [{"name": e["name"], "status": e["status"], "args": e["args"]}
                   for e in events if e["kind"] == "tool_finished"]
        retrieval_ids = {c["id"] for m in agent.messages[len(before):] for c in m.get("tool_calls") or []
                         if c["function"]["name"] == "read_output"}
        retrieved = any(m.get("tool_call_id") in retrieval_ids and m.get("content", "").startswith("status: ok\n")
                        and "RESULT=" + receipt["token"] in m["content"] for m in agent.messages[len(before):])
        return {
            "case": case, "policy": policy, "attempt": attempt,
            "task_passed": grade_recall(result.answer, receipt["token"], exit_code, after["executions"], actions, agent.model.saw_token),
            "run_status": result.status, "answer": result.answer,
            "expected_token": receipt["token"], "expected_exit": exit_code,
            "executions": after["executions"], "retrieved_expected_token": retrieved,
            "model_saw_expected_token": agent.model.saw_token,
            "tool_calls": result.tool_calls, "elapsed_seconds": elapsed,
            "prompt_tokens": result.prompt_tokens, "completion_tokens": result.completion_tokens,
            "contexts": [e for e in events if e["kind"] == "context_built"], "actions": actions,
        }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repeat", type=int, default=3)
    args = parser.parse_args()
    if not 1 <= args.repeat <= 5:
        parser.error("repeat must be 1..5")
    root = Path(__file__).resolve().parents[1]
    config = resolve_config(env_file=root / ".env", provider="deepseek")
    commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip()
    if subprocess.check_output(["git", "status", "--porcelain"], cwd=root, text=True).strip():
        parser.error("commit before running")
    cases = ["retain_requirement", "revised_requirement", "recall_success_log", "recall_failed_log"]
    jobs = [(case, policy, attempt) for attempt in range(1, args.repeat + 1) for case in cases
            for policy in (["budget_only", "historical"] if attempt % 2 else ["historical", "budget_only"])]

    def run(job):
        case, policy, attempt = job
        cls = HistoricalAgent if policy == "historical" else Agent
        if case.startswith("recall_"):
            return recall_attempt(config, case, policy, attempt, cls)
        return run_attempt(config, case, policy, attempt, agent_class=cls)

    report = {
        "at": datetime.now(UTC).isoformat(), "commit": commit, "working_tree_dirty": False,
        "model": config.model, "provider": config.provider, "repeats": args.repeat,
        "budget_chars": 48000, "max_tool_calls": 12,
        "protocol": "Same tasks, tools, model and budgets; only historical log omission differs. "
                    "Scripted setup executes real commands; follow-ups use the live model. "
                    "Recall accepts visible original output or an archive read, and forbids reexecution. "
                    "No temperature or seed override; two workers.",
        "rows": [],
    }
    output = root / "benchmarks" / "results" / ("history-outputs-" + datetime.now(UTC).strftime("%Y%m%d-%H%M%S") + ".json")
    with ThreadPoolExecutor(max_workers=2) as pool:
        futures = [pool.submit(run, job) for job in jobs]
        for job, future in zip(jobs, futures, strict=True):
            try:
                row = future.result()
            except Exception as exc:  # noqa: BLE001 - retain other attempts on infrastructure failure
                row = {"case": job[0], "policy": job[1], "attempt": job[2],
                       "task_passed": False, "infrastructure_error": type(exc).__name__}
            report["rows"].append(row)
            output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            print(f"{job}: passed={row['task_passed']} status={row.get('run_status')} tools={row.get('tool_calls')}", flush=True)
    print(output)


if __name__ == "__main__":
    main()
